sudo: required
dist: trusty
services: docker

before_install:
before_install:
- chmod +x .ci/*.sh
- |
  sed -i 's/3306:3306/3307:3306/g' .ci/docker-run-mysql.sh && \
  ./.ci/docker-run-mysql.sh
- sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
- sudo apt-get update
- sudo apt-get install -y dotnet-dev-1.0.1

script:
- dotnet restore
- dotnet test tests/MySqlConnector.Tests/MySqlConnector.Tests.csproj -c Release -f netcoreapp1.1.1
- dotnet build tests/SideBySide/SideBySide.csproj -c Release -f netcoreapp1.1.1
- echo 'Executing tests with No Compression, No SSL' && ./.ci/use-config.sh config.json 172.17.0.1 3307 && time dotnet test tests/SideBySide/SideBySide.csproj -c Release -f netcoreapp1.1.1
- echo 'Executing tests with Compression, No SSL' && ./.ci/use-config.sh config.compression.json 172.17.0.1 3307 && time dotnet test tests/SideBySide/SideBySide.csproj -c Release -f netcoreapp1.1.1
- echo 'Executing tests with No Compression, SSL' && ./.ci/use-config.sh config.ssl.json 172.17.0.1 3307 && time dotnet test tests/SideBySide/SideBySide.csproj -c Release -f netcoreapp1.1.1
- echo 'Executing tests with Compression, SSL' && ./.ci/use-config.sh config.compression+ssl.json 172.17.0.1 3307 && time dotnet test tests/SideBySide/SideBySide.csproj -c Release -f netcoreapp1.1.1
- echo 'Executing tests with Unix Domain Socket, No Compression, No SSL' && ./.ci/use-config.sh config.uds.json && time dotnet test tests/SideBySide/SideBySide.csproj -c Release -f netcoreapp1.1.1

after_script:
- chmod +x .ci/build-docs.sh && ./.ci/build-docs.sh

notifications:
  slack:
    secure: IHVnvL5z2g75VQt9qmJxpAyrbQQPA8VIaO0Of8q4p733E9aA4ZwuFDiqxXcamBbcFJeVPPq4xBTRPZNlTUyZt+No9oFaDnlIA1fKE/ksVH03SqrXwXO0k6toCqofb0/166+ijoe0m6IV7wfT8lvtgD9Lgd9y+M3Zh2NKXAlJasaOve8/pUOcgDqhfT5MST4RD1X4xdjcNnWifEQHACFWgYsM8bD5SrqbAYkHnUcZx0LnY7Cr2RwTUTFS5EN+lbSmy+uhE+JyYFT/5EBIcjLQql8QIHFanTtlGif5rosxb1Wot7pve6KWCGMUnM7FO5vmCbzeRC/kQZ4VGNQyFW8BrOTpOSOAPDfUvlIKuNsARkIYhHvLfjbNtjlcBuyrBKbuvLmGpYo7w+qUGimpi6xZTr3iq0cpb9OYhEtaF/upWI+p77kjjPYlXCg424zP+5SlTVBwCbOsUsKK/l1SjL8RBgpl/bgMTQ7jzEBO+zAWBW7H50d1edZ1IgyClVYbtwR0/gjJGndYyZLALf55x0FnYQkgCuPXU5egmdBiwQUZcRRcjgzY3s9tXLY2NHjI61Zt6IA4JoAugjH03VTo369gj641bLkH3ViVCLnvI6BPIaTsgjs+g6V00K+PT3+Vu9nnLd6eXc72V5QiWHPEMXyGTdnIYnHm9VvK7879c/W/aTM=
